CREATE TABLE courses (
    code          VARCHAR(20)  PRIMARY KEY,
    title         VARCHAR(120) NOT NULL,
    duration_days INT          NOT NULL,
    seats         INT          NOT NULL
);

CREATE TABLE students (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(60)  NOT NULL,
    last_name  VARCHAR(60)  NOT NULL,
    email      VARCHAR(120) NOT NULL,
    phone      VARCHAR(20)
);

CREATE TABLE registrations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    BIGINT      NOT NULL,
    course_code   VARCHAR(20) NOT NULL,
    registered_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id)  REFERENCES students (id),
    FOREIGN KEY (course_code) REFERENCES courses (code)
);
